services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_ORIGINS=chrome-extension://*
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=1h
      - OLLAMA_CPU_THREADS=16 # Adjust based on your CPU cores
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
      # Add shared memory volume for better performance
      - /dev/shm:/dev/shm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 100G  # Adjust based on your RAM
    # Use NVIDIA Container Toolkit for GPU access
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility